apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
        - name: backend-user
          image: mrtruongminh/udagram-api-user:v0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: env-secret
            - secretRef:
                name: aws-secret
            - configMapRef:
                name: env-configmap

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: backend-user
  name: backend-user
spec:
  ports:
    - name: "8080"
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: backend-user
  type: ClusterIP
status:
  loadBalancer: {}
